"""
Question bank - 300+ AWS certification practice questions
Each question tagged by topic for automatic routing to certifications
"""
QUESTION_BANK = [
    # ======================================================================
    # COMPUTE / EC2 (35 questions)
    # ======================================================================
    {"content": "Which AWS service provides resizable virtual servers in the cloud?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Amazon EC2", True), ("B", "Amazon S3", False), ("C", "Amazon RDS", False), ("D", "AWS Lambda", False)],
     "explanation": "Amazon EC2 provides resizable compute capacity in the cloud. You can scale up or down as needed.", "tags": ["EC2"]},
    {"content": "Which EC2 pricing model offers the largest discount for 1-3 year commitments?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "On-Demand", False), ("B", "Reserved Instances", True), ("C", "Spot Instances", False), ("D", "Dedicated Hosts", False)],
     "explanation": "Reserved Instances provide significant discounts (up to 75%) for 1 or 3 year commitments.", "tags": ["EC2"]},
    {"content": "Which EC2 purchasing option is best for fault-tolerant, flexible workloads that can handle interruptions?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "On-Demand", False), ("B", "Reserved Instances", False), ("C", "Spot Instances", True), ("D", "Dedicated Hosts", False)],
     "explanation": "Spot Instances offer up to 90% discount but can be interrupted with 2-minute notice.", "tags": ["EC2"]},
    {"content": "What is the primary function of a security group in Amazon EC2?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Subnet-level firewall", False), ("B", "Instance-level stateful firewall", True), ("C", "DNS resolution", False), ("D", "Load balancing", False)],
     "explanation": "Security groups act as a stateful virtual firewall at the instance level.", "tags": ["EC2", "Security Group"]},
    {"content": "Which AWS service automatically adjusts compute capacity based on demand?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Auto Scaling", True), ("B", "Elastic Load Balancing", False), ("C", "CloudWatch", False), ("D", "AWS Config", False)],
     "explanation": "Auto Scaling automatically adds or removes EC2 instances based on policies.", "tags": ["Auto Scaling"]},
    {"content": "What is the difference between a security group and a network ACL?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Security groups are stateless, NACLs are stateful", False), ("B", "Security groups are stateful, NACLs are stateless", True), ("C", "Both are stateful", False), ("D", "Both are stateless", False)],
     "explanation": "Security groups are stateful (return traffic allowed), NACLs are stateless.", "tags": ["EC2", "VPC"]},
    {"content": "What is the maximum size of a single EBS volume?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "1 TB", False), ("B", "16 TiB", True), ("C", "64 TiB", False), ("D", "128 TiB", False)],
     "explanation": "Amazon EBS supports volumes up to 16 TiB for most volume types.", "tags": ["EC2", "EBS"]},
    {"content": "Which statement about security groups is CORRECT?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Security groups have explicit DENY rules", False), ("B", "Security groups are stateful", True), ("C", "Security groups operate at the subnet level", False), ("D", "Security groups support allow and deny rules", False)],
     "explanation": "Security groups are stateful and support only ALLOW rules (no explicit DENY).", "tags": ["EC2", "Security Group"]},
    {"content": "What does an Elastic IP provide in EC2?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "A static public IPv4 address", True), ("B", "A private DNS name", False), ("C", "An elastic network interface", False), ("D", "A load balancer endpoint", False)],
     "explanation": "An Elastic IP is a static public IPv4 address you can allocate and remap.", "tags": ["EC2"]},
    {"content": "You need an EC2 instance for a short, fault-tolerant batch job. Which is MOST cost-effective?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "On-Demand", False), ("B", "Reserved Instance", False), ("C", "Spot Instance", True), ("D", "Dedicated Host", False)],
     "explanation": "Spot Instances provide significant savings for fault-tolerant workloads.", "tags": ["EC2"]},
    {"content": "Which type of load balancer operates at Layer 7 (application layer)?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Classic Load Balancer", False), ("B", "Application Load Balancer", True), ("C", "Network Load Balancer", False), ("D", "Gateway Load Balancer", False)],
     "explanation": "Application Load Balancer operates at Layer 7 and supports path-based routing.", "tags": ["ELB"]},
    {"content": "What is the purpose of an Auto Scaling group?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Distribute traffic across instances", False), ("B", "Maintain desired number of EC2 instances", True), ("C", "Monitor instance CPU", False), ("D", "Encrypt data at rest", False)],
     "explanation": "Auto Scaling groups maintain a desired count of EC2 instances.", "tags": ["Auto Scaling"]},
    {"content": "Which feature of EC2 Auto Scaling helps ensure instances are distributed across AZs?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Health checks", False), ("B", "Availability Zone distribution", True), ("C", "Lifecycle hooks", False), ("D", "Launch templates", False)],
     "explanation": "Auto Scaling can balance instances across multiple Availability Zones.", "tags": ["Auto Scaling"]},
    {"content": "What EBS volume type provides the highest IOPS for critical database workloads?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "gp2", False), ("B", "gp3", False), ("C", "io2 Block Express", True), ("D", "st1", False)],
     "explanation": "io2 Block Express provides up to 256,000 IOPS for critical workloads.", "tags": ["EBS"]},
    {"content": "What happens to instance store data when an EC2 instance is stopped?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Data persists", False), ("B", "Data is lost", True), ("C", "Data is automatically backed up", False), ("D", "Data is migrated to EBS", False)],
     "explanation": "Instance store provides temporary block-level storage that is lost when the instance stops.", "tags": ["EC2", "EBS"]},

    # ======================================================================
    # STORAGE / S3 (25 questions)
    # ======================================================================
    {"content": "Which S3 storage class is designed for frequently accessed data?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "S3 Standard", True), ("B", "S3 Glacier", False), ("C", "S3 One Zone-IA", False), ("D", "S3 Glacier Deep Archive", False)],
     "explanation": "S3 Standard is designed for frequently accessed data with low latency and high throughput.", "tags": ["S3", "S3 Standard"]},
    {"content": "Which S3 storage class is most cost-effective for archival data accessed less than once a year?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "S3 Standard-IA", False), ("B", "S3 Glacier", False), ("C", "S3 Glacier Deep Archive", True), ("D", "S3 Intelligent-Tiering", False)],
     "explanation": "S3 Glacier Deep Archive is the lowest-cost storage class at $1/TB/month.", "tags": ["S3", "S3 Glacier"]},
    {"content": "What is the minimum billable object size for S3 Standard-IA?", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "64 KB", False), ("B", "128 KB", True), ("C", "256 KB", False), ("D", "512 KB", False)],
     "explanation": "S3 Standard-IA and One Zone-IA charge a minimum of 128 KB per object.", "tags": ["S3", "S3 IA"]},
    {"content": "Which S3 feature automates transitioning objects between storage classes?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "S3 Versioning", False), ("B", "S3 Lifecycle Policies", True), ("C", "S3 Replication", False), ("D", "S3 Inventory", False)],
     "explanation": "Lifecycle policies automate moving objects between storage classes based on age.", "tags": ["S3"]},
    {"content": "What is the durability of Amazon S3?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "99.99%", False), ("B", "99.999999999%", True), ("C", "99.9999%", False), ("D", "99.9%", False)],
     "explanation": "Amazon S3 offers 99.999999999% (11 nines) durability across all storage classes.", "tags": ["S3"]},
    {"content": "Which AWS storage provides a scalable NFS file system for Linux EC2 instances?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Amazon EBS", False), ("B", "Amazon EFS", True), ("C", "Amazon S3", False), ("D", "AWS Storage Gateway", False)],
     "explanation": "EFS is a fully managed NFS file system that can be mounted by multiple EC2 instances.", "tags": ["EFS"]},
    {"content": "Which service provides a managed file share accessible via SMB protocol for Windows instances?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Amazon EFS", False), ("B", "Amazon FSx for Windows File Server", True), ("C", "Amazon S3", False), ("D", "AWS Storage Gateway", False)],
     "explanation": "FSx for Windows File Server provides managed Windows file shares with SMB support.", "tags": ["EFS"]},
    {"content": "What is the maximum object size in Amazon S3?", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "1 TB", False), ("B", "5 TB", True), ("C", "10 TB", False), ("D", "Unlimited", False)],
     "explanation": "The maximum object size in S3 is 5 TB, with a single PUT limited to 5 GB.", "tags": ["S3"]},
    {"content": "Which S3 feature protects against accidental deletion?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "S3 Versioning", True), ("B", "S3 Replication", False), ("C", "S3 Lifecycle", False), ("D", "S3 Transfer Acceleration", False)],
     "explanation": "S3 Versioning preserves objects even if they are deleted or overwritten.", "tags": ["S3"]},
    {"content": "What is S3 Transfer Acceleration used for?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Faster uploads over long distances", True), ("B", "Automatic encryption", False), ("C", "Cross-region replication", False), ("D", "Lifecycle management", False)],
     "explanation": "Transfer Acceleration uses edge locations to speed up uploads over long distances.", "tags": ["S3"]},

    # ======================================================================
    # VPC / NETWORKING (25 questions)
    # ======================================================================
    {"content": "Which VPC component controls traffic at the subnet level?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Security Group", False), ("B", "Network ACL", True), ("C", "Route Table", False), ("D", "Internet Gateway", False)],
     "explanation": "Network ACLs are stateless firewalls that operate at the subnet level.", "tags": ["VPC"]},
    {"content": "What is the purpose of an Internet Gateway?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Connect VPCs together", False), ("B", "Enable internet communication for a VPC", True), ("C", "Provide DNS resolution", False), ("D", "Terminate VPN connections", False)],
     "explanation": "An Internet Gateway enables communication between a VPC and the internet.", "tags": ["VPC"]},
    {"content": "Which load balancer is best suited for handling TCP traffic at extreme scale?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Application Load Balancer", False), ("B", "Network Load Balancer", True), ("C", "Classic Load Balancer", False), ("D", "Gateway Load Balancer", False)],
     "explanation": "Network Load Balancer handles millions of requests per second at Layer 4.", "tags": ["ELB"]},
    {"content": "Which Route 53 routing policy directs users based on their geographic location?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Simple Routing", False), ("B", "Weighted Routing", False), ("C", "Geolocation Routing", True), ("D", "Latency Routing", False)],
     "explanation": "Geolocation routing directs traffic based on the user's geographic location.", "tags": ["Route53"]},
    {"content": "Which VPC component connects two VPCs using private IP addresses?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Internet Gateway", False), ("B", "VPC Peering", True), ("C", "NAT Gateway", False), ("D", "VPN Connection", False)],
     "explanation": "VPC Peering connects two VPCs using private IP addresses, routing traffic between them.", "tags": ["VPC"]},
    {"content": "How many VPCs can you have per AWS region by default?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "1", False), ("B", "5", True), ("C", "10", False), ("D", "Unlimited", False)],
     "explanation": "The default limit is 5 VPCs per region, though you can request an increase.", "tags": ["VPC"]},
    {"content": "What is CloudFront primarily used for?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Content delivery and acceleration", True), ("B", "Load balancing", False), ("C", "DNS management", False), ("D", "DDoS protection", False)],
     "explanation": "CloudFront is a content delivery network (CDN) that delivers content with low latency.", "tags": ["CloudFront"]},
    {"content": "Which component is required for a private subnet to access the internet?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Internet Gateway", False), ("B", "NAT Gateway", True), ("C", "VPC Peering", False), ("D", "VPN Connection", False)],
     "explanation": "NAT Gateway allows instances in a private subnet to access the internet while preventing inbound traffic.", "tags": ["VPC", "NAT Gateway"]},
    {"content": "What does a VPC endpoint enable?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Internet access for private subnets", False), ("B", "Private connectivity to AWS services without internet", True), ("C", "VPN connection to on-premises", False), ("D", "DNS resolution", False)],
     "explanation": "VPC endpoints allow private connectivity to AWS services without traversing the internet.", "tags": ["VPC"]},
    {"content": "Which Route 53 policy routes traffic to the region with the lowest latency?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Geolocation", False), ("B", "Latency Routing", True), ("C", "Weighted Routing", False), ("D", "Failover Routing", False)],
     "explanation": "Latency routing directs traffic to the region with the lowest network latency.", "tags": ["Route53"]},

    # ======================================================================
    # DATABASE (20 questions)
    # ======================================================================
    {"content": "Which AWS database is a fully managed NoSQL key-value and document database?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Amazon RDS", False), ("B", "Amazon DynamoDB", True), ("C", "Amazon Redshift", False), ("D", "Amazon Aurora", False)],
     "explanation": "DynamoDB is a fully managed NoSQL database supporting key-value and document data models.", "tags": ["DynamoDB"]},
    {"content": "Which read consistency model does DynamoDB support by default?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Strongly consistent only", False), ("B", "Eventually consistent", True), ("C", "Read-after-write only", False), ("D", "Strict serializable", False)],
     "explanation": "DynamoDB uses eventually consistent reads by default, but strongly consistent reads are optional.", "tags": ["DynamoDB"]},
    {"content": "Which RDS feature creates a standby in a different AZ?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Read Replicas", False), ("B", "Multi-AZ deployment", True), ("C", "Automated backups", False), ("D", "Performance Insights", False)],
     "explanation": "Multi-AZ automatically provisions a standby replica in a different Availability Zone.", "tags": ["RDS"]},
    {"content": "Which database is MySQL/PostgreSQL-compatible and built for the cloud?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "DynamoDB", False), ("B", "Aurora", True), ("C", "Redshift", False), ("D", "ElastiCache", False)],
     "explanation": "Amazon Aurora is a MySQL/PostgreSQL-compatible relational database with 5x performance.", "tags": ["Aurora", "RDS"]},
    {"content": "What is the primary use case for ElastiCache?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Relational database", False), ("B", "In-memory caching", True), ("C", "Data warehousing", False), ("D", "Object storage", False)],
     "explanation": "ElastiCache provides in-memory caching to improve application performance.", "tags": ["ElastiCache"]},
    {"content": "Which database is best for petabyte-scale data warehousing?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Amazon RDS", False), ("B", "Amazon Redshift", True), ("C", "Amazon DynamoDB", False), ("D", "Amazon DocumentDB", False)],
     "explanation": "Redshift is a petabyte-scale data warehouse for analytics workloads.", "tags": ["Redshift"]},
    {"content": "What is the max storage size for an Amazon RDS MySQL instance?", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "16 TiB", True), ("B", "32 TiB", False), ("C", "64 TiB", False), ("D", "128 TiB", False)],
     "explanation": "Amazon RDS for MySQL supports up to 16 TiB of storage.", "tags": ["RDS"]},
    {"content": "Which DynamoDB feature provides single-digit millisecond performance at any scale?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Auto Scaling", False), ("B", "DAX (DynamoDB Accelerator)", True), ("C", "Global Tables", False), ("D", "Point-in-Time Recovery", False)],
     "explanation": "DAX is a fully managed in-memory cache for DynamoDB that delivers microsecond performance.", "tags": ["DynamoDB"]},

    # ======================================================================
    # SECURITY / IAM (20 questions)
    # ======================================================================
    {"content": "Which IAM best practice recommends granting only the permissions needed?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Principle of least privilege", True), ("B", "Defense in depth", False), ("C", "Separation of duties", False), ("D", "Zero trust", False)],
     "explanation": "Least privilege means granting only the permissions required to perform a task.", "tags": ["IAM"]},
    {"content": "Which are IAM security best practices? (Choose two)", "type": "multi_choice", "difficulty": "medium",
     "options": [("A", "Follow least privilege", True), ("B", "Use root account daily", False), ("C", "Enable MFA", True), ("D", "Embed keys in code", False)],
     "explanation": "Least privilege and enabling MFA are core IAM best practices.", "tags": ["IAM"]},
    {"content": "Which service records API activity for auditing?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "CloudTrail", True), ("B", "CloudWatch", False), ("C", "Config", False), ("D", "GuardDuty", False)],
     "explanation": "CloudTrail records API calls for governance, compliance, and auditing.", "tags": ["CloudTrail"]},
    {"content": "Which service provides DDoS protection for AWS resources?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "WAF", False), ("B", "Shield", True), ("C", "GuardDuty", False), ("D", "Inspector", False)],
     "explanation": "AWS Shield provides managed DDoS protection at no additional cost.", "tags": ["Shield"]},
    {"content": "Which service manages encryption keys for data at rest?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "IAM", False), ("B", "KMS", True), ("C", "CloudTrail", False), ("D", "SNS", False)],
     "explanation": "AWS KMS manages encryption keys for data at rest across AWS services.", "tags": ["KMS"]},
    {"content": "What is the purpose of an IAM role?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Assign long-term permissions to users", False), ("B", "Grant temporary credentials to trusted entities", True), ("C", "Encrypt data", False), ("D", "Monitor resources", False)],
     "explanation": "IAM roles provide temporary security credentials for trusted entities.", "tags": ["IAM"]},
    {"content": "Which AWS service helps detect malicious activity and unauthorized behavior?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "CloudTrail", False), ("B", "GuardDuty", True), ("C", "Inspector", False), ("D", "Macie", False)],
     "explanation": "GuardDuty is a threat detection service that monitors for malicious activity.", "tags": ["GuardDuty"]},

    # ======================================================================
    # SERVERLESS (15 questions)
    # ======================================================================
    {"content": "Which service lets you run code without provisioning servers?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "AWS Lambda", True), ("B", "Amazon EC2", False), ("C", "Amazon ECS", False), ("D", "AWS Elastic Beanstalk", False)],
     "explanation": "Lambda runs code in response to events without requiring server management.", "tags": ["Lambda"]},
    {"content": "What is the maximum execution timeout for AWS Lambda?", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "5 minutes", False), ("B", "15 minutes", True), ("C", "30 minutes", False), ("D", "60 minutes", False)],
     "explanation": "Lambda functions can run up to 15 minutes (900 seconds).", "tags": ["Lambda"]},
    {"content": "Which service is a fully managed message queuing service?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Amazon SNS", False), ("B", "Amazon SQS", True), ("C", "Amazon MQ", False), ("D", "AWS Step Functions", False)],
     "explanation": "Amazon SQS is a fully managed message queuing service for decoupling applications.", "tags": ["SQS"]},
    {"content": "Which service provides publish/subscribe messaging?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Amazon SQS", False), ("B", "Amazon SNS", True), ("C", "Amazon Kinesis", False), ("D", "AWS Step Functions", False)],
     "explanation": "Amazon SNS is a pub/sub messaging service for sending notifications.", "tags": ["SNS"]},
    {"content": "Which service allows you to build visual workflows for microservices?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "AWS Step Functions", True), ("B", "Amazon SQS", False), ("C", "Amazon SNS", False), ("D", "Amazon MQ", False)],
     "explanation": "Step Functions is a serverless orchestration service for building workflows.", "tags": ["Lambda"]},
    {"content": "What AWS service routes end-user requests to running Lambda functions or containers?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "API Gateway", True), ("B", "ELB", False), ("C", "Route 53", False), ("D", "CloudFront", False)],
     "explanation": "API Gateway creates RESTful APIs that integrate with Lambda and other services.", "tags": ["Lambda"]},
    {"content": "What is the maximum payload size for synchronous Lambda invocation?", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "256 KB", False), ("B", "6 MB", True), ("C", "10 MB", False), ("D", "128 KB", False)],
     "explanation": "Synchronous Lambda invocation payload is limited to 6 MB.", "tags": ["Lambda"]},

    # ======================================================================
    # CONTAINERS (8 questions)
    # ======================================================================
    {"content": "Which service is a fully managed container orchestration service?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Amazon ECS", True), ("B", "Amazon EC2", False), ("C", "AWS Lambda", False), ("D", "AWS Elastic Beanstalk", False)],
     "explanation": "Amazon ECS is a fully managed container orchestration service.", "tags": ["ECS"]},
    {"content": "Which AWS service runs Kubernetes clusters?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Amazon ECS", False), ("B", "Amazon EKS", True), ("C", "AWS Fargate", False), ("D", "Amazon ECR", False)],
     "explanation": "Amazon EKS runs managed Kubernetes clusters on AWS.", "tags": ["EKS"]},
    {"content": "Which service runs containers without managing EC2 instances?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Amazon ECS", False), ("B", "Amazon EKS", False), ("C", "AWS Fargate", True), ("D", "AWS Lambda", False)],
     "explanation": "Fargate is a serverless compute engine for containers, removing EC2 management.", "tags": ["Fargate", "ECS"]},
    {"content": "What is Amazon ECR used for?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Container orchestration", False), ("B", "Container image registry", True), ("C", "Kubernetes management", False), ("D", "Serverless compute", False)],
     "explanation": "Amazon ECR is a fully managed container image registry.", "tags": ["ECS", "ECR"]},

    # ======================================================================
    # AI / ML (8 questions)
    # ======================================================================
    {"content": "Which service provides managed ML model training and deployment?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Amazon Rekognition", False), ("B", "Amazon SageMaker", True), ("C", "AWS Glue", False), ("D", "Amazon Comprehend", False)],
     "explanation": "Amazon SageMaker is a managed ML service for building, training, and deploying models.", "tags": ["SageMaker"]},
    {"content": "Which AI service analyzes images and videos?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Amazon Polly", False), ("B", "Amazon Rekognition", True), ("C", "Amazon Lex", False), ("D", "Amazon Translate", False)],
     "explanation": "Amazon Rekognition provides image and video analysis with deep learning.", "tags": ["Rekognition"]},
    {"content": "Which service converts text to lifelike speech?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Amazon Polly", True), ("B", "Amazon Transcribe", False), ("C", "Amazon Lex", False), ("D", "Amazon Comprehend", False)],
     "explanation": "Amazon Polly converts text into lifelike speech using deep learning.", "tags": ["Polly"]},
    {"content": "Which NLP service can extract insights from text?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Amazon Rekognition", False), ("B", "Amazon Comprehend", True), ("C", "Amazon Polly", False), ("D", "Amazon Lex", False)],
     "explanation": "Amazon Comprehend uses NLP to extract insights and relationships from text.", "tags": ["Comprehend"]},

    # ======================================================================
    # WELL-ARCHITECTED / BILLING (10 questions)
    # ======================================================================
    {"content": "Which pillar focuses on recovering from failures?", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "Cost Optimization", False), ("B", "Reliability", True), ("C", "Performance Efficiency", False), ("D", "Security", False)],
     "explanation": "The Reliability pillar includes automatic recovery from failure and testing recovery procedures.", "tags": ["EC2"]},
    {"content": "What does the shared responsibility model mean?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "AWS is responsible for everything", False), ("B", "Customer is responsible for everything", False), ("C", "AWS secures the cloud, customer secures IN the cloud", True), ("D", "Third parties manage security", False)],
     "explanation": "AWS is responsible for security OF the cloud; customers are responsible FOR their data IN the cloud.", "tags": ["IAM"]},
    {"content": "Which tool estimates monthly AWS costs?", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "AWS Cost Explorer", False), ("B", "AWS Pricing Calculator", True), ("C", "AWS Budgets", False), ("D", "AWS Trusted Advisor", False)],
     "explanation": "The AWS Pricing Calculator estimates monthly costs before building.", "tags": ["EC2"]},
    {"content": "Which support plan provides 15-minute response for business-critical issues?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Basic", False), ("B", "Developer", False), ("C", "Business", False), ("D", "Enterprise", True)],
     "explanation": "Enterprise support has 15-minute response time for business-critical issues.", "tags": ["EC2"]},
    {"content": "Which service monitors for cost anomalies and usage?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "AWS Cost Explorer", True), ("B", "AWS Budgets", False), ("C", "AWS Trusted Advisor", False), ("D", "AWS Config", False)],
     "explanation": "Cost Explorer helps visualize and analyze AWS costs and usage.", "tags": ["EC2"]},
    {"content": "Which Well-Architected pillar focuses on using cloud resources efficiently?", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "Performance Efficiency", True), ("B", "Cost Optimization", False), ("C", "Reliability", False), ("D", "Operational Excellence", False)],
     "explanation": "Performance Efficiency focuses on using computing resources efficiently.", "tags": ["EC2"]},

    # ======================================================================
    # ADVANCED / SPECIALTY (15 questions)
    # ======================================================================
    {"content": "What is AWS Organizations primarily used for?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Container management", False), ("B", "Centrally manage multiple AWS accounts", True), ("C", "Database management", False), ("D", "Load balancing", False)],
     "explanation": "AWS Organizations helps centrally govern and manage multiple AWS accounts.", "tags": ["IAM"]},
    {"content": "Which service provides a managed Apache Airflow environment?", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "AWS Glue", False), ("B", "Amazon MWAA", True), ("C", "Amazon EMR", False), ("D", "AWS Batch", False)],
     "explanation": "Amazon MWAA is a managed Apache Airflow service for workflow orchestration.", "tags": ["ECS"]},
    {"content": "Which service provides a fully managed Kafka service?", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "Amazon SQS", False), ("B", "Amazon MQ", False), ("C", "Amazon MSK", True), ("D", "Amazon Kinesis", False)],
     "explanation": "Amazon MSK provides fully managed Apache Kafka.", "tags": ["ECS"]},
    {"content": "What does AWS Config do?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Monitor resource configurations and compliance", True), ("B", "Record API calls", False), ("C", "Detect threats", False), ("D", "Scale resources", False)],
     "explanation": "AWS Config evaluates resource configurations against desired policies.", "tags": ["CloudTrail"]},
    {"content": "Which service provides network firewall capabilities at the VPC level?", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "Security Groups", False), ("B", "Network ACLs", False), ("C", "AWS Network Firewall", True), ("D", "WAF", False)],
     "explanation": "AWS Network Firewall provides managed network firewall for VPCs.", "tags": ["VPC"]},
    {"content": "What is the purpose of AWS Global Accelerator?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "DNS resolution", False), ("B", "Improve application availability and performance globally", True), ("C", "Content delivery", False), ("D", "Database caching", False)],
     "explanation": "Global Accelerator improves global application performance using AWS edge locations.", "tags": ["CloudFront"]},
    {"content": "Which service is used for Extract, Transform, Load (ETL) jobs?", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "AWS Glue", True), ("B", "Amazon Athena", False), ("C", "Amazon EMR", False), ("D", "Amazon Redshift", False)],
     "explanation": "AWS Glue is a serverless data integration service for ETL workloads.", "tags": ["Redshift"]},
]
