"""
CloudCert Pro - 中文题库
覆盖 AWS 13 个认证的常见考点，题目内容为中文，专业名词保留英文。
"""
QUESTION_BANK_ZH = [
    # ==================== 计算 / EC2 ====================
    {"content": "以下哪个 AWS 服务提供可弹性伸缩的云服务器？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Amazon EC2", True), ("B", "Amazon S3", False), ("C", "Amazon RDS", False), ("D", "AWS Lambda", False)],
     "explanation": "Amazon EC2 (Elastic Compute Cloud) 提供可伸缩的云服务器，您可以根据需要快速扩展或缩减计算资源。", "tags": ["EC2"]},
    {"content": "哪种 EC2 定价模式适合容错能力强、可中断的弹性工作负载？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "按需 (On-Demand)", False), ("B", "预留实例 (Reserved Instances)", False), ("C", "Spot 实例", True), ("D", "专用主机 (Dedicated Host)", False)],
     "explanation": "Spot 实例最高可享受 90% 折扣，但可能被中断（2分钟通知），适合容错和弹性工作负载。", "tags": ["EC2"]},
    {"content": "安全组 (Security Group) 和网络 ACL 的主要区别是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "安全组无状态，NACL 有状态", False), ("B", "安全组有状态，NACL 无状态", True), ("C", "两者都有状态", False), ("D", "两者都无状态", False)],
     "explanation": "安全组是有状态的（允许返回流量自动通过），NACL 是无状态的（需要显式配置入站和出站规则）。", "tags": ["EC2", "VPC"]},
    {"content": "以下哪个是安全组的正确描述？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "安全组有显式的拒绝规则", False), ("B", "安全组是有状态的", True), ("C", "安全组作用于子网级别", False), ("D", "安全组同时支持允许和拒绝规则", False)],
     "explanation": "安全组是有状态的，只支持允许规则（没有显式拒绝规则），作用于实例级别。", "tags": ["EC2", "Security Group"]},
    {"content": "一个公司的生产 Web 应用运行在 Application Load Balancer 后面的 EC2 实例上，流量波动较大。哪种方案性价比最高且可扩展？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "始终预置峰值容量的 EC2 实例", False), ("B", "使用 Auto Scaling 配合基于 CPU 的目标追踪策略", True), ("C", "在高峰期手动添加 EC2 实例", False), ("D", "使用更大的实例类型处理所有流量", False)],
     "explanation": "Auto Scaling 配合目标追踪策略可根据需求自动调整容量，优化成本和性能，符合 Well-Architected 的弹性原则。", "tags": ["EC2", "Auto Scaling"]},
    {"content": "哪种 EC2 预留实例类型允许更改实例属性？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "标准预留实例 (Standard RI)", False), ("B", "可转换预留实例 (Convertible RI)", True), ("C", "计划预留实例 (Scheduled RI)", False), ("D", "区域预留实例", False)],
     "explanation": "Convertible RI 允许更改实例类型、操作系统等属性，但折扣略低于 Standard RI。", "tags": ["EC2"]},
    {"content": "弹性 IP (Elastic IP) 的特点是什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "静态公网 IPv4 地址", True), ("B", "私有 DNS 名称", False), ("C", "弹性网络接口", False), ("D", "负载均衡端点", False)],
     "explanation": "弹性 IP 是可以动态关联和解绑的静态公网 IPv4 地址，未关联运行实例时会收费。", "tags": ["EC2"]},
    {"content": "实例存储 (Instance Store) 在 EC2 实例停止后数据会怎样？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "数据持久保留", False), ("B", "数据丢失", True), ("C", "数据自动备份到 S3", False), ("D", "数据迁移到 EBS", False)],
     "explanation": "实例存储提供临时块级存储，实例停止或终止后数据会丢失。", "tags": ["EC2", "EBS"]},
    {"content": "一个数据库工作负载需要高随机 I/O 性能，运行在单台 EC2 实例上。哪种存储方案最适合？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Amazon S3", False), ("B", "Amazon EBS Provisioned IOPS (io2)", True), ("C", "Amazon EFS", False), ("D", "EC2 实例存储", False)],
     "explanation": "EBS io2 卷为数据库工作负载提供高 IOPS 和低延迟。实例存储是临时的，S3 是对象存储，EFS 是文件系统。", "tags": ["EC2", "EBS"]},
    {"content": "Auto Scaling 有什么作用？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "在实例之间分发流量", False), ("B", "维持所需的 EC2 实例数量", True), ("C", "监控实例 CPU", False), ("D", "加密静态数据", False)],
     "explanation": "Auto Scaling 自动调整 EC2 实例数量以匹配应用需求，确保有足够的容量处理负载。", "tags": ["Auto Scaling"]},
    {"content": "Application Load Balancer 工作在 OSI 模型的哪一层？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "第 3 层（网络层）", False), ("B", "第 4 层（传输层）", False), ("C", "第 7 层（应用层）", True), ("D", "第 2 层（数据链路层）", False)],
     "explanation": "ALB 工作在应用层（第7层），支持基于路径和主机的路由以及 HTTP/HTTPS 协议。", "tags": ["ELB"]},
    {"content": "哪种负载均衡器支持静态 IP 地址？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Application Load Balancer", False), ("B", "Network Load Balancer", True), ("C", "Classic Load Balancer", False), ("D", "Gateway Load Balancer", False)],
     "explanation": "NLB 工作在传输层（第4层），支持静态 IP 和弹性 IP 地址，可处理数百万请求。", "tags": ["ELB"]},

    # ==================== 存储 / S3 ====================
    {"content": "哪个 S3 存储类专为频繁访问的数据设计？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "S3 Standard", True), ("B", "S3 Glacier", False), ("C", "S3 One Zone-IA", False), ("D", "S3 Glacier Deep Archive", False)],
     "explanation": "S3 Standard 专为频繁访问的数据设计，提供低延迟和高吞吐性能。", "tags": ["S3", "S3 Standard"]},
    {"content": "S3 的持久性是多少？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "99.99%", False), ("B", "99.999999999%（11 个 9）", True), ("C", "99.9999%", False), ("D", "99.9%", False)],
     "explanation": "Amazon S3 在所有存储类中提供 99.999999999%（11 个 9）的持久性。", "tags": ["S3"]},
    {"content": "哪个 S3 功能可以自动在不同存储类之间转换对象？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "S3 版本控制", False), ("B", "S3 生命周期策略", True), ("C", "S3 复制", False), ("D", "S3 清单", False)],
     "explanation": "生命周期策略根据对象创建时间自动将对象在不同存储类之间转换，例如 30 天后转为 Standard-IA。", "tags": ["S3"]},
    {"content": "S3 的最大对象大小是多少？", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "1 TB", False), ("B", "5 TB", True), ("C", "10 TB", False), ("D", "无限制", False)],
     "explanation": "S3 单个对象最大为 5TB，大于 100MB 的对象建议使用分片上传 (Multipart Upload)。", "tags": ["S3"]},
    {"content": "以下哪个是 S3 的数据保护功能？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "自动扩缩容", False), ("B", "版本控制", True), ("C", "自动补丁", False), ("D", "连接池", False)],
     "explanation": "S3 版本控制保留对象的所有版本（包括删除标记），可防止意外删除或覆盖。", "tags": ["S3"]},
    {"content": "哪种存储服务为 Linux EC2 实例提供可扩展的 NFS 文件系统？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Amazon EBS", False), ("B", "Amazon EFS", True), ("C", "Amazon S3", False), ("D", "AWS Storage Gateway", False)],
     "explanation": "EFS 是完全托管的 NFS 文件系统，可被多个 EC2 实例同时挂载，自动扩展到 PB 级。", "tags": ["EFS"]},
    {"content": "哪种 EBS 卷类型提供最高 IOPS 性能？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "gp3", False), ("B", "io2 Block Express", True), ("C", "st1", False), ("D", "sc1", False)],
     "explanation": "io2 Block Express 提供高达 256,000 IOPS，适合关键业务数据库如 SAP HANA 和 Oracle。", "tags": ["EBS"]},

    # ==================== 网络 / VPC ====================
    {"content": "VPC 中的互联网网关 (IGW) 有什么作用？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "在 VPC 之间建立连接", False), ("B", "实现 VPC 与互联网通信", True), ("C", "提供 DNS 解析", False), ("D", "加密数据传输", False)],
     "explanation": "互联网网关 (IGW) 是 VPC 与互联网之间的通信桥梁，允许公网流量进入 VPC。", "tags": ["VPC"]},
    {"content": "NAT 网关的作用是什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "阻止恶意流量进入 VPC", False), ("B", "允许私有子网实例访问互联网", True), ("C", "负载均衡实例流量", False), ("D", "监控网络流量", False)],
     "explanation": "NAT 网关使私有子网中的 EC2 实例能够访问互联网（如下载更新），但阻止互联网主动连接实例。", "tags": ["VPC"]},
    {"content": "VPC 对等连接 (Peering) 不支持以下哪个特性？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "跨区域连接", False), ("B", "传递路由 (Transitive Routing)", True), ("C", "跨账户连接", False), ("D", "私有 IP 通信", False)],
     "explanation": "VPC Peering 不支持传递路由。如果 A 与 B 对等、B 与 C 对等，A 不能通过 B 与 C 通信。Transit Gateway 支持传递路由。", "tags": ["VPC"]},
    {"content": "哪种 AWS 服务提供专用的私有网络连接，将本地数据中心连接到 AWS？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "AWS VPN", False), ("B", "AWS Direct Connect", True), ("C", "VPC Peering", False), ("D", "AWS Transit Gateway", False)],
     "explanation": "Direct Connect 提供从本地到 AWS 的专用物理连接（1-100 Gbps），具有一致的网络性能和较低的带宽成本。", "tags": ["VPC", "Direct Connect"]},
    {"content": "Transit Gateway 的主要优势是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "提供内容分发网络", False), ("B", "通过中心辐射架构连接多个 VPC", True), ("C", "提供 DDoS 保护", False), ("D", "管理数据库连接", False)],
     "explanation": "Transit Gateway 通过中心辐射架构连接数千个 VPC 和本地网络，支持传递路由。", "tags": ["VPC"]},
    {"content": "VPC 端点 (Endpoint) 的作用是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "将 VPC 连接到互联网", False), ("B", "在不经过互联网的情况下私密连接到 AWS 服务", True), ("C", "提供 DNS 服务", False), ("D", "监控 API 调用", False)],
     "explanation": "VPC Endpoint 允许您在 VPC 内私密访问 AWS 服务，无需经过互联网或 NAT 网关。", "tags": ["VPC"]},
    {"content": "CloudFront 是什么类型的服务？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "内容分发网络 (CDN)", True), ("B", "对象存储服务", False), ("C", "关系型数据库", False), ("D", "DNS 服务", False)],
     "explanation": "Amazon CloudFront 是全球内容分发网络 (CDN)，通过 450+ 边缘节点加速内容分发。", "tags": ["CloudFront", "CDN"]},

    # ==================== 数据库 ====================
    {"content": "Amazon RDS 支持以下哪些数据库引擎？", "type": "multi_choice", "difficulty": "easy",
     "options": [("A", "MySQL", True), ("B", "PostgreSQL", True), ("C", "Redis", False), ("D", "MongoDB", False)],
     "explanation": "RDS 支持 Aurora、MySQL、PostgreSQL、SQL Server、Oracle 和 MariaDB。Redis 是 ElastiCache，MongoDB 是 DocumentDB。", "tags": ["RDS"]},
    {"content": "RDS Multi-AZ 部署的主要目的是什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "提升读取性能", False), ("B", "提供高可用性和自动故障转移", True), ("C", "跨区域复制数据", False), ("D", "创建数据库备份", False)],
     "explanation": "Multi-AZ 在另一个可用区维护同步备用副本，发生故障时自动切换（通常 < 60 秒）。", "tags": ["RDS"]},
    {"content": "RDS 只读副本 (Read Replica) 有什么限制？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "不能跨区域部署", False), ("B", "异步复制，可能有轻微延迟", True), ("C", "最多支持 5 个副本", False), ("D", "不能提升为主库", False)],
     "explanation": "只读副本使用异步复制，最多 15 个，可跨区域部署，可提升为独立主库。", "tags": ["RDS"]},
    {"content": "DynamoDB 是什么类型的数据库？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "关系型数据库", False), ("B", "键值对和文档型 NoSQL 数据库", True), ("C", "图数据库", False), ("D", "时序数据库", False)],
     "explanation": "DynamoDB 是全托管 NoSQL 键值对和文档数据库，个位数毫秒级延迟，自动扩缩容。", "tags": ["DynamoDB"]},
    {"content": "DynamoDB Accelerator (DAX) 的作用是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "提供 ACID 事务", False), ("B", "作为 DynamoDB 的内存缓存，微秒级延迟", True), ("C", "跨区域复制数据", False), ("D", "自动创建备份", False)],
     "explanation": "DAX 是 DynamoDB 的内存缓存，提供微秒级的读取延迟，对现有应用程序兼容。", "tags": ["DynamoDB"]},
    {"content": "DynamoDB 全局二级索引 (GSI) 的特点是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "使用不同的分区键和排序键", True), ("B", "只能在创建表时定义", False), ("C", "支持强一致性读取", False), ("D", "每表最多 5 个", False)],
     "explanation": "GSI 允许使用不同的分区键和排序键查询数据，创建表后可添加或删除，每表最多 20 个（可提升）。", "tags": ["DynamoDB"]},
    {"content": "Amazon Aurora 与标准 MySQL 相比性能提高多少？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "2 倍", False), ("B", "3 倍", False), ("C", "5 倍", True), ("D", "10 倍", False)],
     "explanation": "Aurora 提供比标准 MySQL 高 5 倍的性能，存储自动扩展到 128TB，兼容 MySQL 和 PostgreSQL。", "tags": ["Aurora", "RDS"]},
    {"content": "Amazon ElastiCache 支持哪些缓存引擎？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Redis 和 Memcached", True), ("B", "MySQL 和 PostgreSQL", False), ("C", "MongoDB 和 Cassandra", False), ("D", "DynamoDB 和 DAX", False)],
     "explanation": "ElastiCache 支持 Redis（丰富数据结构、持久化、复制）和 Memcached（简单键值缓存）。", "tags": ["ElastiCache"]},

    # ==================== 安全 ====================
    {"content": "AWS IAM 的核心组件包括哪些？", "type": "multi_choice", "difficulty": "easy",
     "options": [("A", "用户 (User)", True), ("B", "组 (Group)", True), ("C", "角色 (Role)", True), ("D", "数据库 (Database)", False)],
     "explanation": "IAM 的三个核心组件是用户（代表个人或服务）、组（用户集合简化权限管理）和角色（临时权限）。", "tags": ["IAM"]},
    {"content": "以下哪项是保护 AWS 根账户的最佳实践？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "日常使用根账户登录", False), ("B", "为根账户启用 MFA", True), ("C", "为根账户创建访问密钥", False), ("D", "将根账户密码设为简单密码", False)],
     "explanation": "根账户应启用 MFA，不创建访问密钥，避免日常使用，仅用于账户管理操作。", "tags": ["IAM"]},
    {"content": "服务控制策略 (SCP) 的作用是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "管理 EC2 实例的自动扩缩容", False), ("B", "在 AWS Organizations 中设置账户级权限上限", True), ("C", "监控网络流量", False), ("D", "自动备份数据", False)],
     "explanation": "SCP 在 Organizations 中为成员账户设置权限上限，作为统一的安全护栏。", "tags": ["IAM"]},
    {"content": "AWS KMS 的主要功能是什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "创建和控制加密密钥", True), ("B", "管理用户密码", False), ("C", "监控 API 调用", False), ("D", "检测恶意活动", False)],
     "explanation": "KMS 是创建和控制加密密钥的托管服务，与 100+ AWS 服务集成，支持自动轮换。", "tags": ["KMS"]},
    {"content": "AWS CloudTrail 的作用是什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "自动扩缩容", False), ("B", "记录 AWS API 调用活动供审计", True), ("C", "分发内容", False), ("D", "运行无服务器代码", False)],
     "explanation": "CloudTrail 记录 AWS 账户中的 API 活动，提供事件历史用于安全审计和合规性。", "tags": ["CloudTrail"]},
    {"content": "AWS Shield Standard 提供什么级别的保护？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "免费自动 DDoS 保护", True), ("B", "付费 WAF 规则", False), ("C", "流量加密", False), ("D", "数据库加密", False)],
     "explanation": "Shield Standard 为所有 AWS 用户免费提供自动网络和传输层 DDoS 保护。", "tags": ["Shield"]},
    {"content": "Amazon GuardDuty 如何检测威胁？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "扫描 EC2 实例漏洞", False), ("B", "使用机器学习分析 VPC Flow Logs、CloudTrail 和 DNS 日志", True), ("C", "检查 S3 桶权限", False), ("D", "评估资源配置合规性", False)],
     "explanation": "GuardDuty 使用 ML 分析 VPC Flow Logs、CloudTrail 事件和 DNS 日志来检测异常行为。", "tags": ["GuardDuty"]},
    {"content": "AWS WAF 可以防御哪些攻击？", "type": "multi_choice", "difficulty": "medium",
     "options": [("A", "SQL 注入", True), ("B", "跨站脚本攻击 (XSS)", True), ("C", "DDoS 攻击", False), ("D", "中间人攻击", False)],
     "explanation": "WAF 保护 Web 应用免受 SQL 注入和 XSS 攻击。DDoS 防护由 Shield 提供。", "tags": ["WAF"]},
    {"content": "IAM 角色的临时安全凭证由哪个服务颁发？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "AWS KMS", False), ("B", "AWS STS (Security Token Service)", True), ("C", "AWS CloudHSM", False), ("D", "AWS ACM", False)],
     "explanation": "AWS STS 为 IAM 角色颁发临时安全凭证，用于跨账户访问和联合身份验证。", "tags": ["IAM"]},
    {"content": "Amazon Inspector 的功能是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "自动发现和扫描 EC2 实例漏洞", True), ("B", "记录 API 调用", False), ("C", "提供内容分发", False), ("D", "管理数据库", False)],
     "explanation": "Inspector 自动扫描 EC2 实例和容器镜像中的 CVE 漏洞和网络可达性问题。", "tags": ["Security"]},

    # ==================== 无服务器 ====================
    {"content": "AWS Lambda 的最大执行超时时间是多少？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "5 分钟", False), ("B", "15 分钟", True), ("C", "30 分钟", False), ("D", "1 小时", False)],
     "explanation": "Lambda 函数最长执行 900 秒（15 分钟），包括初始化时间和执行时间。", "tags": ["Lambda"]},
    {"content": "以下哪些可以触发 Lambda 函数？", "type": "multi_choice", "difficulty": "medium",
     "options": [("A", "S3 事件通知", True), ("B", "DynamoDB Streams", True), ("C", "API Gateway", True), ("D", "EC2 实例启动", False)],
     "explanation": "Lambda 可由 S3 事件、DynamoDB Streams、API Gateway、SNS、Kinesis 等多种源触发。", "tags": ["Lambda"]},
    {"content": "Lambda 冷启动优化的方法包括哪些？", "type": "multi_choice", "difficulty": "medium",
     "options": [("A", "减少函数包体积", True), ("B", "使用 Lambda Layers", True), ("C", "使用更大的实例类型", False), ("D", "使用预置并发 (Provisioned Concurrency)", True)],
     "explanation": "减少包体积、使用 Layers、选择较快运行时（Python/Node.js）、使用预置并发和 SnapStart 都可优化冷启动。", "tags": ["Lambda"]},
    {"content": "Amazon SQS 队列的类型有哪些？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "标准队列和 FIFO 队列", True), ("B", "只读队列和读写队列", False), ("C", "主队列和从队列", False), ("D", "同步队列和异步队列", False)],
     "explanation": "SQS 支持标准队列（至少一次交付，高吞吐）和 FIFO 队列（严格一次处理，顺序保证）。", "tags": ["SQS"]},
    {"content": "Amazon SNS 的推送模式叫什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "点对点", False), ("B", "发布/订阅 (Pub/Sub)", True), ("C", "请求/响应", False), ("D", "队列模式", False)],
     "explanation": "SNS 采用发布/订阅模式，一条消息可推送给多个订阅者（SQS、Lambda、Email、HTTP 等）。", "tags": ["SNS"]},
    {"content": "API Gateway 支持创建什么类型的 API？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "仅 REST API", False), ("B", "REST API 和 WebSocket API", True), ("C", "仅 GraphQL API", False), ("D", "仅 SOAP API", False)],
     "explanation": "API Gateway 支持创建 RESTful API 和 WebSocket API，用于构建无服务器后端。", "tags": ["Lambda", "Serverless"]},

    # ==================== 容器 ====================
    {"content": "Amazon ECS 的启动类型有哪些？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Fargate 和 EC2", True), ("B", "Lambda 和 Step Functions", False), ("C", "Kubernetes 和 Docker", False), ("D", "ECS 和 EKS", False)],
     "explanation": "ECS 支持 Fargate（无服务器，无需管理服务器）和 EC2（精细控制实例配置）两种启动类型。", "tags": ["ECS"]},
    {"content": "AWS Fargate 的特点是什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "需要在 EC2 上安装 Docker", False), ("B", "无需管理底层服务器即可运行容器", True), ("C", "仅支持 Windows 容器", False), ("D", "需要手动扩缩容", False)],
     "explanation": "Fargate 是无服务器容器计算引擎，您只需定义任务规格，无需管理底层 EC2 实例。", "tags": ["Fargate"]},
    {"content": "Amazon EKS 的作用是什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "运行和管理 Kubernetes 集群", True), ("B", "提供对象存储", False), ("C", "管理关系型数据库", False), ("D", "监控 API 调用", False)],
     "explanation": "EKS 是托管的 Kubernetes 服务，自动管理控制平面，支持现有的 Kubernetes 工具和插件。", "tags": ["EKS"]},

    # ==================== Well-Architected ====================
    {"content": "AWS Well-Architected Framework 包含几个支柱？", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "5 个", False), ("B", "6 个", True), ("C", "7 个", False), ("D", "4 个", False)],
     "explanation": "Well-Architected Framework 有 6 个支柱：卓越运营、安全、可靠性、性能效率、成本优化和可持续性。", "tags": ["EC2"]},
    {"content": "AWS Trusted Advisor 提供哪些检查？", "type": "multi_choice", "difficulty": "medium",
     "options": [("A", "成本优化", True), ("B", "安全性", True), ("C", "容错能力", True), ("D", "数据库性能", False)],
     "explanation": "Trusted Advisor 提供成本优化、安全性、容错能力和性能方面的检查和建议。", "tags": ["EC2"]},
    {"content": "AWS 免费套餐包含哪些内容？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "每月 750 小时 EC2 t2.micro", True), ("B", "无限 EC2 实例", False), ("C", "免费 RDS 数据库", False), ("D", "免费 Premium Support", False)],
     "explanation": "AWS 免费套餐包括每月 750 小时 EC2 t2.micro、5GB S3 存储、25GB DynamoDB 等。", "tags": ["EC2"]},

    # ==================== AI/ML ====================
    {"content": "Amazon SageMaker 涵盖的 ML 流程包括哪些？", "type": "multi_choice", "difficulty": "medium",
     "options": [("A", "数据标注 (Ground Truth)", True), ("B", "模型训练", True), ("C", "模型部署", True), ("D", "成本管理", False)],
     "explanation": "SageMaker 覆盖完整 ML 生命周期：数据标注、构建、训练、调优、部署和监控。", "tags": ["SageMaker"]},
    {"content": "Amazon Rekognition 提供什么功能？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "图像和视频分析", True), ("B", "自然语言处理", False), ("C", "语音转文本", False), ("D", "机器翻译", False)],
     "explanation": "Rekognition 提供图像和视频分析，包括物体检测、人脸识别和内容审核。", "tags": ["Rekognition"]},
    {"content": "Amazon Comprehend 是什么类型的服务？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "计算机视觉服务", False), ("B", "自然语言处理 (NLP) 服务", True), ("C", "语音合成服务", False), ("D", "机器学习平台", False)],
     "explanation": "Comprehend 是 NLP 服务，可提取实体、情感分析和关键词。", "tags": ["Comprehend"]},
    {"content": "Amazon Polly 的功能是什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "将文本转换为逼真的语音", True), ("B", "将语音转换为文本", False), ("C", "图像识别", False), ("D", "机器翻译", False)],
     "explanation": "Polly 将文本转换为自然的语音，支持多种语言和声音。", "tags": ["Polly"]},
    {"content": "Amazon Redshift 是什么类型的服务？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "关系型数据库", False), ("B", "PB 级数据仓库", True), ("C", "NoSQL 数据库", False), ("D", "内存缓存", False)],
     "explanation": "Redshift 是 PB 级数据仓库，使用列式存储，适合大规模分析查询。", "tags": ["Redshift"]},

    # ==================== DevOps ====================
    {"content": "AWS CodePipeline 的作用是什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "管理基础设施配置", False), ("B", "自动化 CI/CD 流水线", True), ("C", "监控应用性能", False), ("D", "管理数据库迁移", False)],
     "explanation": "CodePipeline 是完全托管的 CI/CD 服务，可自动化构建、测试和部署流程。", "tags": ["EC2"]},
    {"content": "AWS CloudFormation 的作用是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "以代码形式管理 AWS 基础设施", True), ("B", "监控应用日志", False), ("C", "自动扩缩容", False), ("D", "内容分发", False)],
     "explanation": "CloudFormation 通过模板以基础设施即代码 (IaC) 方式创建和管理 AWS 资源。", "tags": ["EC2"]},

    # ==================== 核心场景题 ====================
    {"content": "一家公司需要静态网站托管，要求全球低延迟和高可用性。哪种方案最经济高效？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "EC2 实例 + ALB", False), ("B", "S3 静态网站托管 + CloudFront", True), ("C", "ECS + Fargate", False), ("D", "Elastic Beanstalk", False)],
     "explanation": "S3 静态网站托管成本极低，配合 CloudFront 全球 CDN 加速，实现全球低延迟访问。", "tags": ["S3", "CloudFront"]},
    {"content": "一家金融公司需要在 S3 中加密敏感数据，要求使用自己的密钥管理。应该使用哪种加密方式？", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "SSE-S3", False), ("B", "SSE-KMS (客户托管密钥)", True), ("C", "SSE-C", False), ("D", "不加密", False)],
     "explanation": "SSE-KMS 使用客户托管密钥，提供审计日志和细粒度控制，适合合规性要求高的场景。", "tags": ["S3", "KMS"]},
    {"content": "公司的 MySQL 数据库流量不可预测，需要自动扩缩容。哪种解决方案最合适？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "在 EC2 上自建 MySQL 并手动管理", False), ("B", "使用 Aurora Serverless", True), ("C", "使用 RDS 单实例", False), ("D", "使用 DynamoDB", False)],
     "explanation": "Aurora Serverless 自动启动、扩缩容和关闭数据库容量，适合不可预测的工作负载。", "tags": ["Aurora", "RDS"]},
    {"content": "公司需要将 50TB 数据从本地数据中心迁移到 AWS。网络带宽有限。哪种迁移方法最快？", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "通过 VPN 使用 AWS CLI 上传", False), ("B", "使用 AWS Snowball 设备", True), ("C", "使用 S3 Transfer Acceleration", False), ("D", "使用 Direct Connect", False)],
     "explanation": "对于大量数据迁移，Snowball 物理设备比网络传输更快。50TB 通过 1Gbps 网络需要约 5 天。", "tags": ["S3"]},
    {"content": "一家公司需要为其 Web 应用提供跨多个可用区的高可用架构。最佳实践是？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "在单个可用区部署多个实例", False), ("B", "使用 ALB + 跨多个可用区的 Auto Scaling 组", True), ("C", "只使用一台大型 EC2 实例", False), ("D", "使用 CloudFront 访问本地服务器", False)],
     "explanation": "ALB 结合跨多个可用区的 Auto Scaling 是高可用架构的最佳实践，可自动故障转移。", "tags": ["EC2", "ELB", "Auto Scaling"]},
    {"content": "AWS 责任共担模型中，客户负责什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "物理服务器安全", False), ("B", "客户数据和操作系统配置", True), ("C", "网络基础设施", False), ("D", "数据中心的物理安全", False)],
     "explanation": "AWS 负责云基础设施的安全（物理安全、网络等），客户负责云中的数据安全、OS 配置和访问管理。", "tags": ["IAM", "Security"]},

    # ==================== 更多 EC2 / 网络 / 存储补充 ====================
    {"content": "哪种 Route 53 路由策略适合在不同区域间分配流量以实现最低延迟？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "简单路由", False), ("B", "延迟路由 (Latency-based)", True), ("C", "加权路由", False), ("D", "故障转移路由", False)],
     "explanation": "延迟路由将用户路由到延迟最低的区域，基于区域间的网络测量。", "tags": ["Route53"]},
    {"content": "Route 53 故障转移路由需要配合什么使用？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "Auto Scaling", False), ("B", "健康检查 (Health Check)", True), ("C", "CloudWatch 告警", False), ("D", "负载均衡器", False)],
     "explanation": "故障转移路由结合健康检查实现主备切换，健康检查失败时自动将流量路由到备用。", "tags": ["Route53"]},
    {"content": "ECS 任务的原子部署单元是什么？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "ECS 服务", False), ("B", "ECS 任务 (Task)", True), ("C", "ECS 集群", False), ("D", "容器实例", False)],
     "explanation": "ECS 任务是 ECS 中的原子部署单元，定义为一个或多个容器组成的组。", "tags": ["ECS"]},
    {"content": "哪种 EC2 实例适合需要 GPU 加速的机器学习训练？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "t3.medium", False), ("B", "c5.large", False), ("C", "p4d.xlarge", True), ("D", "r5.large", False)],
     "explanation": "p4d 实例配备 NVIDIA GPU，专为 ML 训练和 HPC 工作负载设计。", "tags": ["EC2"]},
    {"content": "EBS 快照存储在哪个服务中？", "type": "single_choice", "difficulty": "easy",
     "options": [("A", "Amazon EBS", False), ("B", "Amazon S3", True), ("C", "Amazon EFS", False), ("D", "AWS Backup", False)],
     "explanation": "EBS 快照以增量方式存储在 Amazon S3 中，具有 11 个 9 的持久性。", "tags": ["EBS", "S3"]},
    {"content": "当您需要将 EBS 卷从 100GB gp2 升级到 500GB gp3 时，需要停机吗？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "需要停机", False), ("B", "无需停机，可在线修改", True), ("C", "需要创建新卷并迁移数据", False), ("D", "只能在实例停止时修改", False)],
     "explanation": "EBS 支持在线修改卷类型、大小和 IOPS，无需停机。", "tags": ["EBS"]},
    {"content": "S3 标准存储和 S3 标准-IA 的关键区别是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "IA 需要 30 天最短存储期", True), ("B", "IA 不可用", False), ("C", "IA 仅存储在一个可用区", False), ("D", "IA 延迟更高", False)],
     "explanation": "Standard-IA 适合低频访问数据，有 30 天最短存储期和取回费用，但读取延迟与 Standard 相同。", "tags": ["S3"]},
    {"content": "CloudFront 签名 URL 的作用是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "加速内容上传", False), ("B", "限时授权访问受保护内容", True), ("C", "提高缓存命中率", False), ("D", "压缩传输内容", False)],
     "explanation": "签名 URL 提供对受保护内容的临时访问权限，常用于付费内容分发。", "tags": ["CloudFront"]},
    {"content": "以下哪个是 AWS 数据库迁移服务 (DMS) 支持的迁移类型？", "type": "single_choice", "difficulty": "hard",
     "options": [("A", "同构迁移（如 MySQL 到 MySQL）", False), ("B", "异构迁移（如 Oracle 到 Aurora）", False), ("C", "持续复制", False), ("D", "以上全部", True)],
     "explanation": "DMS 支持同构和异构数据库迁移，以及持续的变更数据捕获 (CDC) 复制。", "tags": ["RDS", "Database"]},
    {"content": "AWS Config 的主要用途是什么？", "type": "single_choice", "difficulty": "medium",
     "options": [("A", "自动扩缩容", False), ("B", "持续评估资源配置是否符合预期策略", True), ("C", "记录 API 调用", False), ("D", "检测恶意活动", False)],
     "explanation": "AWS Config 评估资源配置是否符合预期策略，提供合规性检查。", "tags": ["Security"]},
]
